CREATE DATABASE inlock_games_tarde;
GO

USE inlock_games_tarde;
GO

CREATE TABLE ESTUDIO (
	 idEstudio SMALLINT PRIMARY KEY IDENTITY(1,1),
	 nomeEstudio VARCHAR(30) NOT NULL
);


CREATE TABLE JOGO (
		idJogo 	SMALLINT PRIMARY KEY IDENTITY(1,1),
		idEstudio SMALLINT FOREIGN KEY REFERENCES ESTUDIO(idEstudio),
		nomeJogo VARCHAR(100) NOT NULL,
		descrição VARCHAR(256),
		dataLancamento DATETIME NOT NULL,
		valor REAL NOT NULL
);

CREATE TABLE TIPO_USUARIO (
		idTipoUsuario SMALLINT PRIMARY KEY IDENTITY(1,1),
		titulo VARCHAR(100)
);

CREATE TABLE USUARIO (
		idUsuario SMALLINT PRIMARY KEY IDENTITY (1,1),
		idTipoUsuario SMALLINT FOREIGN KEY REFERENCES TIPO_USUARIO(idTipoUsuario),
		email VARCHAR(256) NOT NULL UNIQUE,
		senha VARCHAR(25) NOT NULL
)




