SELECT * FROM USUARIOS 

SELECT * FROM ESTUDIOS

SELECT * FROM JOGOS

SELECT * FROM JOGOS
INNER JOIN ESTUDIOS
ON JOGOS.idEstudio = ESTUDIOS.idEstudio;
GO

SELECT * FROM ESTUDIOS
LEFT JOIN JOGOS
ON ESTUDIOS.idEstudio = JOGOS.idEstudio;
GO

SELECT * FROM USUARIOS
WHERE email = 'cliente@cliente.com' AND senha = 'cliente';
GO

SELECT * FROM JOGOS
WHERE idJogo = 2;
GO

SELECT * FROM ESTUDIOS
WHERE idEstudio = 3;
GO